project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ssapre2
      - icon: twitter
        href: https://twitter.com/sameersapre_9
format:
  html:
    theme: solar
    css: styles.css



